challenge1:challenge1.o
	gcc challenge1.o -o challenge1

challenge1.o:challenge1.cpp
	gcc -c challenge1.cpp

challenge1_i:challenge1_i.o
	gcc challenge1_i.o -o challenge1_i

challenge1_i.o:challenge1_i.cpp
	gcc -c challenge1_i.cpp